TERMUX_PKG_HOMEPAGE=https://github.com/MagicStack/uvloop
TERMUX_PKG_DESCRIPTION="Ultra fast asyncio event loop"
TERMUX_PKG_LICENSE="MIT OR Apache-2.0"
TERMUX_PKG_LICENSE_FILE="LICENSE-APACHE, LICENSE-MIT"
TERMUX_PKG_MAINTAINER="@luuluka"
TERMUX_PKG_VERSION="0.22.1"
TERMUX_PKG_SRCURL=https://pypi.io/packages/source/u/uvloop/uvloop-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=6c84bae345b9147082b17371e3dd5d42775bddce91f885499017f4607fdaf39f
TERMUX_PKG_DEPENDS="python, python-pip"
TERMUX_PKG_PYTHON_COMMON_BUILD_DEPS="'Cython~=3.0'"
TERMUX_PKG_BUILD_IN_SRC=true